server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: block-service
          uri: lb://BLOCK-SERVICE
          predicates:
            - Path=/block-service/**
        - id: purchase-service
          uri: lb://PURCHASE-SERVICE
          predicates:
            - Path=/purchase-service/**
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/**
        - id: webtoon-service
          uri: lb://WEBTOON-SERVICE
          predicates:
            - Path=/webtoon-service/**
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/**
